"""
Every test that executes or reads a contract runs once per pair.

contracts/ holds the frozen pair, deployed on studionet. contracts/v06/ holds
the same files ported to the runtime Studio Next runs, generated by
scripts/port.py, with contracts/v06/PORT.diff as the whole difference. A test in
one of harness.CONTRACT_MODULES runs twice, its id ending [frozen] or [v06], so
a defence that holds in one pair and not the other fails by name.

The other modules test things that are not a contract, or that belong to one
pair on purpose. test_freeze holds the first pair to its hashes and test_port
holds the second to being exactly the port of the first; the parity and
design tests read constants that the port does not touch, from the first pair.
"""

from __future__ import annotations

import pytest

import harness


def pytest_generate_tests(metafunc):
    if metafunc.module.__name__.rpartition(".")[2] in harness.CONTRACT_MODULES:
        metafunc.parametrize("pair", sorted(harness.PAIRS), indirect=True)


@pytest.fixture(autouse=True)
def pair(request):
    chosen = getattr(request, "param", "frozen")
    previous = harness.PAIR
    harness.PAIR = chosen
    yield chosen
    harness.PAIR = previous
